FROM debian:11.5
RUN apt-get update && apt-get install -y init locales vim git openssh-server ntpdate curl unzip zip tar && \
    apt-get install ibus ibus-gtk ibus-pinyin ttf-wqy-zenhei -y && touch /root/.bashrc && \
    echo "export LANG=zh_CN.UTF-8" >> ~/.bashrc &&\
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    curl -s "https://get.sdkman.io" | bash  && source "/root/.sdkman/bin/sdkman-init.sh" &&\
    mkdir -p /var/run/sshd && apt-get clean all
#ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa -q
#~/.ssh/authorized_keys
#-v /sys/fs/cgroup:/sys/fs/cgroup:ro
CMD ["/sbin/init"]
