FROM wumingq/debian:11.5
RUN apt-get update && apt-get install -y init git openssh-server ntpdate curl unzip zip   && \
    apt-get install ibus ibus-gtk ibus-pinyin ttf-wqy-zenhei -y && \
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    curl -s "https://get.sdkman.io" | bash  &&\
    mkdir -p /var/run/sshd && apt-get clean all \
RUN set -eux; \
        	\
        	apkArch="$(dpkg --print-architecture)"; \
        	case "$apkArch" in \
        		amd64|x86_64) \
        			url='https://download.docker.com/linux/static/stable/x86_64/docker-20.10.18.tgz'; \
        			;; \
        		'armhf') \
        			url='https://download.docker.com/linux/static/stable/armel/docker-20.10.18.tgz'; \
        			;; \
        		'armv7') \
        			url='https://download.docker.com/linux/static/stable/armhf/docker-20.10.18.tgz'; \
        			;; \
        		'aarch64') \
        			url='https://download.docker.com/linux/static/stable/aarch64/docker-20.10.18.tgz'; \
        			;; \
        		*) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;; \
        	esac; \
        	\
        	wget -O 'docker.tgz' "$url"; \
        	\
        	tar --extract \
        		--file docker.tgz \
        		--strip-components 1 \
        		--directory /usr/local/bin/ \
        		--no-same-owner \
        		'docker/docker' \
        	; \
        	rm docker.tgz; \
        	\
        	docker --version; \
    \
	case "$apkArch" in \
		amd64|x86_64) \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-amd64'; \
			sha256='a7fb95177792ca8ffc7243fad7bf2f33738b8b999a184b6201f002a63c43d136'; \
			;; \
		'armhf') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-arm-v6'; \
			sha256='159925b4e679eb66e7f0312c7d57a97e68a418c1fa602a00dd8b29b6406768f0'; \
			;; \
		'armv7') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-arm-v7'; \
			sha256='ba8e5359ce9ba24fec6da07f73591c1b20ac0797a2248b0ef8088f57ae3340fc'; \
			;; \
		'aarch64') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-arm64'; \
			sha256='bbf6a76bf9aef9c5759ff225b97ce23a24fc11e4fa3cdcae36e5dcf1de2cffc5'; \
			;; \
		'ppc64le') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-ppc64le'; \
			sha256='1b2441886e556c720c1bf12f18f240113cc45f9eb404c0f162166ca1c96c1b60'; \
			;; \
		'riscv64') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-riscv64'; \
			sha256='c32372dad653fc70eb756b2cffd026e74425e807c01accaeed4559da881ff57c'; \
			;; \
		's390x') \
			url='https://github.com/docker/buildx/releases/download/v0.9.1/buildx-v0.9.1.linux-s390x'; \
			sha256='90b0ecf315d741888920dddeac9fe2e141123c4fe79465b7b10fe23521c9c366'; \
			;; \
		*) echo >&2 "warning: unsupported 'docker-buildx' architecture ($apkArch); skipping"; exit 0 ;; \
	esac; \
	\
	wget -O 'docker-buildx' "$url"; \
	echo "$sha256 *"'docker-buildx' | sha256sum -c -; \
	\
	plugin='/usr/libexec/docker/cli-plugins/docker-buildx'; \
	mkdir -p "$(dirname "$plugin")"; \
	mv -vT 'docker-buildx' "$plugin"; \
	chmod +x "$plugin"; \
	\
	docker buildx version

#ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa -q
#~/.ssh/authorized_keys
#-v /sys/fs/cgroup:/sys/fs/cgroup:ro
CMD ["/sbin/init"]
