FROM debian:11.5
RUN apt-get update && apt-get install -y init locales vim git openssh-server ntpdate wget curl unzip zip tar && \
    apt-get install ibus ibus-gtk ibus-pinyin ttf-wqy-zenhei -y && touch /root/.bashrc && \
    echo "export LANG=zh_CN.UTF-8" >> ~/.bashrc &&\
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash && \
    curl -s "https://get.sdkman.io" | bash  &&\
    mkdir -p /var/run/sshd && apt-get clean all \
RUN set -eux; \
        	\
        	apkArch="$(dpkg --print-architecture)"; \
        	case "$apkArch" in \
        		'x86_64') \
        			url='https://download.docker.com/linux/static/stable/x86_64/docker-20.10.18.tgz'; \
        			;; \
        		'armhf') \
        			url='https://download.docker.com/linux/static/stable/armel/docker-20.10.18.tgz'; \
        			;; \
        		'armv7') \
        			url='https://download.docker.com/linux/static/stable/armhf/docker-20.10.18.tgz'; \
        			;; \
        		'aarch64') \
        			url='https://download.docker.com/linux/static/stable/aarch64/docker-20.10.18.tgz'; \
        			;; \
        		*) echo >&2 "error: unsupported 'docker.tgz' architecture ($apkArch)"; exit 1 ;; \
        	esac; \
        	\
        	wget -O 'docker.tgz' "$url"; \
        	\
        	tar --extract \
        		--file docker.tgz \
        		--strip-components 1 \
        		--directory /usr/local/bin/ \
        		--no-same-owner \
        		'docker/docker' \
        	; \
        	rm docker.tgz; \
        	\
        	docker --version \
#ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa -q
#~/.ssh/authorized_keys
#-v /sys/fs/cgroup:/sys/fs/cgroup:ro
CMD ["/sbin/init"]
