name: adoptium-maven-JDK
on:
  push:
    paths:
      - 'adoptium-maven/Dockerfile-3.8.6-8'
      - 'adoptium-maven/Dockerfile-3.8.6-17'
      - 'adoptium-maven/Dockerfile-debian-3.8.6-8'
      - 'adoptium-maven/Dockerfile-debian-3.8.6-17'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to Ali Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.MY_DOCKER_HUB_USN }}
          password: ${{ secrets.MY_DOCKER_HUB_PWD }}
      - name: 构建 jdk 17  maven 最新版本
        uses: docker/build-push-action@v2
        with:
          context: adoptium-maven/
          file: adoptium-maven/Dockerfile-3.8.6-17
          platforms: linux/amd64
          push: true
          tags: |
            wumingq/apache-maven:3.8.6-adoptiumjdk17
            wumingq/apache-maven:latest
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:3.8.6-adoptiumjdk17
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:latest
      - name: 构建 jdk 8  maven 最新版本
        uses: docker/build-push-action@v2
        with:
          context: adoptium-maven/
          file: adoptium-maven/Dockerfile-3.8.6-8
          platforms: linux/amd64
          push: true
          tags: |
            wumingq/apache-maven:3.8.6-adoptiumjdk8
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:3.8.6-adoptiumjdk8
      - name: 构建 jdk 17  maven 最新版本
        uses: docker/build-push-action@v2
        with:
          context: adoptium-maven/
          file: adoptium-maven/Dockerfile-debian-3.8.6-17
          platforms: linux/amd64
          push: true
          tags: |
            wumingq/apache-maven:debian-3.8.6-adoptiumjdk17
            wumingq/apache-maven:debian-latest
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:debian-3.8.6-adoptiumjdk17
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:debian-latest
      - name: 构建 jdk 8  maven 最新版本
        uses: docker/build-push-action@v2
        with:
          context: adoptium-maven/
          file: adoptium-maven/Dockerfile-debian-3.8.6-8
          platforms: linux/amd64
          push: true
          tags: |
            wumingq/apache-maven:debian-3.8.6-adoptiumjdk8
            registry.cn-hangzhou.aliyuncs.com/wumingq/apache-maven:debian-3.8.6-adoptiumjdk8





