name: adoptium-JDK
on:
  workflow_dispatch:
  push:
    paths:
       - 'adoptium/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dockerfile
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to Ali Docker Hub
        uses: docker/login-action@v1
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.MY_DOCKER_HUB_USN }}
          password: ${{ secrets.MY_DOCKER_HUB_PWD }}
      - name: Build and Push Docker Iamge
        uses: docker/build-push-action@v2
        with:
          context: adoptium/
          platforms: linux/amd64
          push: true
          tags: |
            wumingq/adoptiumjdk:17.0.3-jdk
            wumingq/adoptiumjdk:latest
            registry.cn-hangzhou.aliyuncs.com/wumingq/adoptiumjdk:17.0.3-jdk
            registry.cn-hangzhou.aliyuncs.com/wumingq/adoptiumjdk:latest
  his:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Dockerfile
          uses: actions/checkout@v2
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Log in to Ali Docker Hub
          uses: docker/login-action@v1
          with:
            registry: registry.cn-hangzhou.aliyuncs.com
            username: ${{ secrets.MY_DOCKER_HUB_USN }}
            password: ${{ secrets.MY_DOCKER_HUB_PWD }}
        - name: Build 8u332
          uses: docker/build-push-action@v2
          with:
            context: adoptium/
            file: adoptium/Dockerfile-8u332
            platforms: linux/amd64
            push: true
            tags:  |
              wumingq/adoptiumjdk:8u332-jdk
              registry.cn-hangzhou.aliyuncs.com/wumingq/adoptiumjdk:8u332-jdk





